version: '3.2'

services:
  traefik:
    image: traefik
    command: --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - bacabs-frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    volumes:
      - ./dashboard:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-frontend
      - bacabs-backend
    labels:
      - "traefik.backend=bacabs"
      - "traefik.docker.network=qa-application"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=4200"

  dashboard-backend:
    build:
      context: ./dashboard-backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./dashboard-backend:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-backend

  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    networks:
      - bacabs-backend
    volumes:
      - redis_data:/data

  docker-event-watcher:
    build:
      context: ./docker-event-watcher/
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-event-watcher:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-backend

volumes:
  shared:
    driver: local

  redis_data:
    driver: local

networks:
  bacabs-frontend:
    external: true
  bacabs-backend:
    driver: overlay
