version: '3.2'

services:
  traefik:
    image: traefik
    command: --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - qa-application
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    volumes:
      - ./dashboard:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - qa-application
      - qa-backend
    labels:
      - "traefik.backend=bacabs"
      - "traefik.docker.network=qa-application"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=4200"

  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    networks:
      - qa-backend
    volumes:
      - redis_data:/data

  docker-event-watcher:
    build:
      context: ./docker-event-watcher/
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-event-watcher:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - qa-backend

  gitlab-webhook-receiver:
    build:
      context: ./gitlab-webhook-receiver/
      dockerfile: Dockerfile-dev
    volumes:
      - ./gitlab-webhook-receiver:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - qa-application
      - qa-backend
    labels:
      - "traefik.backend=gitlab"
      - "traefik.docker.network=qa-application"
      - "traefik.frontend.rule=Host:gitlab.localhost"
      - "traefik.port=80"

volumes:
  shared:
    driver: local

  redis_data:
    driver: local

networks:
  qa-application:
    external: true
  qa-backend:
    driver: overlay
