version: '2'

services:
  redis:
    image: redis:3.0
  dashboard:
    build: ./dashboard/
    ports:
      - 80:3000
  docker-event-watcher:
    build: ./docker-event-watcher/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
