version: '3.2'

services:
  traefik:
    image: traefik
    command: --web --docker
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - bacabs-frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  dashboard:
    image: node:latest
    command: bash -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./dashboard-new:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-frontend
      - bacabs-backend
    labels:
      traefik.backend: bacabs
      traefik.docker.network: bacabs-frontend
      traefik.frontend.rule: PathPrefix:/
      traefik.port: "3000"

  dashboard-backend:
    build:
      context: ./dashboard-backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./dashboard-backend:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-frontend
      - bacabs-backend
    labels:
      traefik.backend: bacabs-backend
      traefik.docker.network: bacabs-frontend
      traefik.frontend.rule: PathPrefix:/api,/events
      traefik.port: "3000"

  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    networks:
      - bacabs-backend
    volumes:
      - redis_data:/data

  docker-event-watcher:
    build:
      context: ./docker-event-watcher/
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-event-watcher:/app:rw,cached
      - ./shared:/shared:rw,cached
    networks:
      - bacabs-backend

volumes:
  shared:
    driver: local

  redis_data:
    driver: local

networks:
  bacabs-frontend:
    external: true
  bacabs-backend:
    driver: overlay
