version: '2'

services:
  shared:
    image: tianon/true
    volumes:
      - ./shared:/shared
  redis:
    image: redis:3.0
  dashboard:
    build:
      context: ./dashboard/
      dockerfile: Dockerfile-dev
    ports:
      - 80:3000
    volumes:
      - ./dashboard:/app
    volumes_from:
      - shared
  docker-event-watcher:
    build:
      context: ./docker-event-watcher/
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-event-watcher:/app
    volumes_from:
      - shared
  gitlab-webhook-receiver:
    build:
      context: ./gitlab-webhook-receiver/
      dockerfile: Dockerfile-dev
    volumes:
      - ./gitlab-webhook-receiver:/app
    ports:
      - 8080:80
    volumes_from:
      - shared
